### PR TITLE
Fix dropped key

### LINKED ISSUE #362: Error in insulation_score()
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  :
  Join results in 772081250 rows; more than 46324875 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.

I meet the problem above when I run the function insulation_score()

H1 = load_contacts(signal_path = 'H1.cool')
H1_insulation = insulation_score(H1, window = 25)
r$> H1
A GENOVA contacts object named 'H1.cool' at a resolution of 5 kb.
Contains the following slots:
- MAT   :       Triplet format matrix containing 222128249 informative bins.
- IDX   :       617665 genomic indices in BED format.
- CHRS  :       A vector of 24 chromosome names.
- CENTROMERES:  Locations of 24 centromeres.
This object is assigned the colour 'black'
0 bins are masked.
No chromosomes have been removed.
The data have not been Z-score normalised.
The original data were loaded in as balanced data.

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #362.

I think messing around `options(datatable.allow.cartesian=TRUE)` is the wrong approach here.
This PR ensures proper keys are set and the join is considered valid.

### CODE REVIEW

File: R/insulation_score.R [hunk 1]
```diff
@@ -67,6 +67,7 @@ insulation_score <- function(explist, window = 30,
   outer_bins <- CJ(V1 = bins, V2 = (ext_window - 1):(window))
   outer_bins <- outer_bins[, grp := V1 + V2 - window]
   inner_bins <- outer_bins[, list(V1, V2 = V2 - window, grp)]
```
Comment (teunbrand) [inline R/insulation_score.R:69]: Since a recent update in data.table, the `inner_bins` variable no longer has V1 and V2 as keys. I presume that is because we have mutated V2.

**Comment by robinweide** [comment]
Great! Simple enough fix and explicitly setting keys even helps readability :)
